// These constants represent the RISC-V ELF and the image ID generated by risc0-build.
// The ELF is used for proving and the ID is used for verification.
use ethers::prelude::*;
// use ethers::utils::hash_message;
use ethers::core::utils::hash_message;
use methods::{ANON_HOLDER_GUEST_ELF, ANON_HOLDER_GUEST_ID};
use risc0_zkvm::serde::to_vec;
use risc0_zkvm::{default_prover, ExecutorEnv};

#[tokio::main]
async fn main() {
    // Initialize tracing. In order to view logs, run `RUST_LOG=info cargo run`
    tracing_subscriber::fmt()
        .with_env_filter(tracing_subscriber::filter::EnvFilter::from_default_env())
        .init();

    let wallet = LocalWallet::new(&mut rand::thread_rng());
    println!("Wallet: {}", wallet.address());
    let mut owners: Vec<Address> = (0..5).map(|_| Address::random()).collect();
    owners.push(wallet.address());
    println!("Owners: {:?}", owners);
    let nft_address = Address::random();
    println!("NFT Contract: {}", nft_address);
    let block = 10u32;
    let message = format!("Confirm ownership of {} at block {}", nft_address, block);
    let signature = wallet
        .sign_message(message.clone())
        .await
        .expect("Failed to sign");
    println!("Message: {}", message);
    println!("Signature: {}", signature);

    let message_hash = hash_message(&message);
    let env = ExecutorEnv::builder()
        .write(&message_hash)
        .unwrap()
        .write(&signature)
        .unwrap()
        .write(&owners)
        .unwrap()
        .build()
        .unwrap();

    // Obtain the default prover.
    let prover = default_prover();

    // Proof information by proving the specified ELF binary.
    // This struct contains the receipt along with statistics about execution of the guest
    let prove_info = prover.prove(env, ANON_HOLDER_GUEST_ELF).unwrap();

    // extract the receipt.
    let receipt = prove_info.receipt;

    // TODO: Implement code for retrieving receipt journal here.
    let receipt_bytes = to_vec(&receipt).unwrap();
    println!("Receipt size: {} bytes", receipt_bytes.len());

    // For example:
    let _owners: Vec<Address> = receipt.journal.decode().unwrap();
    println!("{:?}", _owners);
    // The receipt was verified at the end of proving, but the below code is an
    // example of how someone else could verify this receipt.
    receipt.verify(ANON_HOLDER_GUEST_ID).unwrap();

    println!("success");
}
